### ISSUE TITLE
Add support of "ansible" language file

### ISSUE THREAD

**Issue by Sispheor** [bammab/vscode-snippets-for-ansible#2]
Hi,

The [Ansible plugin](https://marketplace.visualstudio.com/items?itemName=tomaciazek.ansible) switch file mode to "ansible" instead of yaml. And so this extension is not usable with it.
Would it be possible to add other extension like "ansible" and "yml" ?

Thanks.

**Comment by netopsengineer** [comment]
@bammab I came here to look for this issue, or post it myself, definitely would love to see this feature added!

**Comment by bammab** [comment]
Done and published as v1.1.0 on vscode markplace and openvsx. Sorry, but I was a bit busy the last weeks...

**Comment by netopsengineer** [comment]
No problem @bammab thanks for implementing this!

**Comment by Sispheor** [comment]
Thanks !
